const express = require("express");
const QRCode = require("qrcode");
const blockchainService = require("../services/blockchainService");
const { requireAuth, requireRole } = require("../middleware/auth");
const { requireBlockchainRole } = require("../middleware/blockchainAuth");
const { clientError, parsePositiveUint } = require("../utils/validation");

const router = express.Router();

function asyncRoute(handler) {
    return (req, res, next) => Promise.resolve(handler(req, res, next)).catch(next);
}

async function qrForBatch(batch) {
    const baseUrl = (process.env.PUBLIC_VERIFY_BASE_URL || "http://localhost:5173/verify").replace(/\/$/, "");
    const verificationUrl = `${baseUrl}/${encodeURIComponent(batch.batchId)}`;
    const qrCodeDataUrl = await QRCode.toDataURL(verificationUrl, {
        errorCorrectionLevel: "M",
        margin: 2,
        width: 512
    });
    return { verificationUrl, qrCodeDataUrl };
}

router.get(
    "/ready-for-sale",
    requireAuth,
    requireRole("CONSUMER"),
    asyncRoute(async (req, res) => {
        const nextBatchId = BigInt(await blockchainService.getNextBatchId());
        const batches = [];
        for (let id = 1n; id < nextBatchId; id += 1n) {
            const batch = await blockchainService.getBatch(id.toString());
            if (batch.statusName !== "READY_FOR_SALE") {
                continue;
            }
            batches.push({
                batch,
                ...(await qrForBatch(batch))
            });
        }
        res.json({ success: true, source: "blockchain", batches });
    })
);

router.post(
    "/:id/qr",
    requireAuth,
    requireRole("RETAILER"),
    requireBlockchainRole("RETAILER"),
    asyncRoute(async (req, res) => {
        const batch = await blockchainService.getBatch(parsePositiveUint(req.params.id, "batchId"));
        if (batch.statusName !== "READY_FOR_SALE" ||
            batch.currentCustodian.toLowerCase() !== req.user.walletAddress.toLowerCase()) {
            throw clientError("QR codes can only be generated by the retailer holding a READY_FOR_SALE batch", 400);
        }

        const { verificationUrl, qrCodeDataUrl } = await qrForBatch(batch);

        res.json({
            success: true,
            batchId: batch.batchId,
            verificationUrl,
            qrCodeDataUrl
        });
    })
);

module.exports = router;
